class FoldersLookup():
    by_borough = '.\\data_store\\by_borough'
    findings_folder = '.\\findings'
    findings_by_weekday = 'by_weekday'
    findings_by_vehicle_type = 'by_vehicle_type'
    input_data = '.\\input_data'
    output_data = '.\\output_data'
    findings_by_time_of_day = 'by_time_of_day'
    findings_by_vehicle_type_kill = 'by_vehicle_type_kill'
    findings_by_vehicle_type_injured = 'by_vehicle_type_injured'